/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Sources */
        get: operations["data_sources_api_data_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/impact/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impact Grid */
        get: operations["impact_grid_api_impact_grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_api_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        /** Update Scenario */
        patch: operations["update_scenario_api_scenarios__scenario_id__patch"];
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Scenario */
        post: operations["evaluate_scenario_api_scenarios__scenario_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Facilities */
        get: operations["list_facilities_api_scenarios__scenario_id__facilities_get"];
        put?: never;
        /** Add Facility */
        post: operations["add_facility_api_scenarios__scenario_id__facilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/facilities/{facility_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Facility */
        delete: operations["delete_facility_api_scenarios__scenario_id__facilities__facility_id__delete"];
        options?: never;
        head?: never;
        /** Update Facility */
        patch: operations["update_facility_api_scenarios__scenario_id__facilities__facility_id__patch"];
        trace?: never;
    };
    "/api/storms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storms */
        get: operations["storms_api_storms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storm Detail */
        get: operations["storm_detail_api_storms__storm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}/impact/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storm Impact */
        get: operations["storm_impact_api_storms__storm_id__impact_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storm Track */
        get: operations["storm_track_api_storms__storm_id__track_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}/wind/frames/{frame_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wind Frame */
        get: operations["wind_frame_api_storms__storm_id__wind_frames__frame_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}/wind/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wind Manifest */
        get: operations["wind_manifest_api_storms__storm_id__wind_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms/{storm_id}/wind/sample-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sample Wind Frame */
        get: operations["sample_wind_frame_api_storms__storm_id__wind_sample_frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taiwan/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taiwan Facilities */
        get: operations["taiwan_facilities_api_taiwan_facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taiwan/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taiwan Zones */
        get: operations["taiwan_zones_api_taiwan_zones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trajectory-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trajectory Match */
        post: operations["trajectory_match_api_trajectory_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wind/periods/{period_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period Wind Manifest */
        get: operations["period_wind_manifest_api_wind_periods__period_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Basin
         * @enum {string}
         */
        Basin: "NA" | "SA" | "WP" | "EP" | "NI" | "SI" | "SP" | "AU" | "XX";
        /**
         * CapacityUnit
         * @enum {string}
         */
        CapacityUnit: "people" | "beds" | "teams" | "people_day";
        /** DataSource */
        DataSource: {
            /**
             * Accessed At
             * @default null
             */
            accessed_at: string | null;
            /** Id */
            id: string;
            /**
             * License Name
             * @default null
             */
            license_name: string | null;
            /** Name */
            name: string;
            /** Purpose */
            purpose: string;
            /** Status */
            status: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** DataSourceListResponse */
        DataSourceListResponse: {
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["DataSource"][];
        };
        /**
         * DataStatus
         * @enum {string}
         */
        DataStatus: "observed" | "reanalysis" | "reported" | "modeled" | "mixed" | "synthetic_fixture" | "synthetic_demo" | "algorithmic_result" | "scenario_model";
        /** EvaluationRequest */
        EvaluationRequest: {
            /**
             * At Risk Population
             * @default 100000
             */
            at_risk_population: number;
            /**
             * Hazard Threshold
             * @default 0.5
             */
            hazard_threshold: number;
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /** Assumptions */
            assumptions: string[];
            /** At Risk Population */
            at_risk_population: number;
            /** By Type */
            by_type?: components["schemas"]["FacilityTypeEvaluation"][];
            /**
             * Covered Population Per Budget Point
             * @default null
             */
            covered_population_per_budget_point: number | null;
            /**
             * Data Status
             * @default scenario_model
             * @constant
             */
            data_status: "scenario_model";
            /** Facility Count */
            facility_count: number;
            /** Modeled Coverage Ratio */
            modeled_coverage_ratio: number;
            /** Modeled Covered Population */
            modeled_covered_population: number;
            /** Modeled Uncovered Population */
            modeled_uncovered_population: number;
            /** Scenario Id */
            scenario_id: string;
            /** Total Budget Points */
            total_budget_points: number;
        };
        /** FacilityCollection */
        FacilityCollection: {
            data_status: components["schemas"]["DataStatus"];
            /** Features */
            features: components["schemas"]["FacilityFeature"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** FacilityCreate */
        FacilityCreate: {
            /**
             * Budget Points
             * @default null
             */
            budget_points: number | null;
            /** @default null */
            capacity_unit: components["schemas"]["CapacityUnit"] | null;
            /**
             * Capacity Value
             * @default null
             */
            capacity_value: number | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Service Radius Km
             * @default null
             */
            service_radius_km: number | null;
            type: components["schemas"]["FacilityType"];
        };
        /** FacilityFeature */
        FacilityFeature: {
            geometry: components["schemas"]["PointGeometry"];
            /**
             * Id
             * @default null
             */
            id: string | null;
            properties: components["schemas"]["FacilityProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** FacilityProperties */
        FacilityProperties: {
            /**
             * Address
             * @default null
             */
            address: string | null;
            /**
             * Budget Points
             * @default null
             */
            budget_points: number | null;
            /** @default null */
            capacity_unit: components["schemas"]["CapacityUnit"] | null;
            /**
             * Capacity Value
             * @default null
             */
            capacity_value: number | null;
            /**
             * County Code
             * @default null
             */
            county_code: string | null;
            data_status: components["schemas"]["DataStatus"];
            /** Facility Id */
            facility_id: string;
            /**
             * Is Simulated
             * @default false
             */
            is_simulated: boolean;
            /** Name */
            name: string;
            /** Service Radius Km */
            service_radius_km: number;
            /** Source Ids */
            source_ids?: string[];
            type: components["schemas"]["FacilityType"];
        };
        /** FacilityRead */
        FacilityRead: {
            /**
             * Budget Points
             * @default null
             */
            budget_points: number | null;
            /** @default null */
            capacity_unit: components["schemas"]["CapacityUnit"] | null;
            /**
             * Capacity Value
             * @default null
             */
            capacity_value: number | null;
            /** Id */
            id: string;
            /** Is Simulated */
            is_simulated: boolean;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Scenario Id */
            scenario_id: string;
            /**
             * Service Radius Km
             * @default null
             */
            service_radius_km: number | null;
            type: components["schemas"]["FacilityType"];
        };
        /**
         * FacilityType
         * @enum {string}
         */
        FacilityType: "shelter" | "medical" | "rescue" | "warehouse";
        /** FacilityTypeEvaluation */
        FacilityTypeEvaluation: {
            capacity_unit: components["schemas"]["CapacityUnit"];
            /** Capacity Value */
            capacity_value: number;
            /** Facility Count */
            facility_count: number;
            /** Modeled Reachable Population */
            modeled_reachable_population: number;
            type: components["schemas"]["FacilityType"];
        };
        /** FacilityUpdate */
        FacilityUpdate: {
            /**
             * Budget Points
             * @default null
             */
            budget_points: number | null;
            /** @default null */
            capacity_unit: components["schemas"]["CapacityUnit"] | null;
            /**
             * Capacity Value
             * @default null
             */
            capacity_value: number | null;
            /**
             * Lat
             * @default null
             */
            lat: number | null;
            /**
             * Lon
             * @default null
             */
            lon: number | null;
            /**
             * Service Radius Km
             * @default null
             */
            service_radius_km: number | null;
            /** @default null */
            type: components["schemas"]["FacilityType"] | null;
        };
        /** GeoBounds */
        GeoBounds: {
            /**
             * Crosses Antimeridian
             * @default false
             */
            crosses_antimeridian: boolean;
            /** East */
            east: number;
            /** North */
            north: number;
            /** South */
            south: number;
            /** West */
            west: number;
        };
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "fixture" | "processed";
            data_status: components["schemas"]["DataStatus"];
            /**
             * Database
             * @constant
             */
            database: "sqlite";
            /** Sample Data */
            sample_data: boolean;
            /**
             * Service
             * @constant
             */
            service: "cyclonescope-api";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImpactGridCollection */
        ImpactGridCollection: {
            data_status: components["schemas"]["DataStatus"];
            /** Features */
            features: components["schemas"]["ImpactGridFeature"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Metric
             * @enum {string}
             */
            metric: "hazard_index" | "max_wind_ms" | "precip_mm" | "population" | "exposed_population" | "reported_damage_usd";
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** ImpactGridFeature */
        ImpactGridFeature: {
            /** Geometry */
            geometry: components["schemas"]["PolygonGeometry"] | components["schemas"]["MultiPolygonGeometry"];
            /**
             * Id
             * @default null
             */
            id: string | null;
            properties: components["schemas"]["ImpactGridProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** ImpactGridProperties */
        ImpactGridProperties: {
            /** Cell Id */
            cell_id: string;
            /** Contributing Storm Ids */
            contributing_storm_ids?: string[];
            data_status: components["schemas"]["DataStatus"];
            /**
             * Exposed Population
             * @default null
             */
            exposed_population: number | null;
            /**
             * Hazard Index
             * @default null
             */
            hazard_index: number | null;
            /**
             * Max Wind Ms
             * @default null
             */
            max_wind_ms: number | null;
            /**
             * Population
             * @default null
             */
            population: number | null;
            /**
             * Precip Mm
             * @default null
             */
            precip_mm: number | null;
            /**
             * Reported Damage Price Year
             * @default null
             */
            reported_damage_price_year: number | null;
            /**
             * Reported Damage Usd
             * @default null
             */
            reported_damage_usd: number | null;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Time End
             * Format: date-time
             */
            time_end: string;
            /**
             * Time Start
             * Format: date-time
             */
            time_start: string;
        };
        /** MultiPolygonGeometry */
        MultiPolygonGeometry: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPolygon";
        };
        /** NormalizedPoint */
        NormalizedPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ];
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
        };
        /** PolygonGeometry */
        PolygonGeometry: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Polygon";
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /** Name */
            name: string;
        };
        /** ScenarioDetail */
        ScenarioDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Facilities */
            facilities?: components["schemas"]["FacilityRead"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ScenarioRead */
        ScenarioRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ScenarioUpdate */
        ScenarioUpdate: {
            /** Name */
            name: string;
        };
        /** StormCatalogResponse */
        StormCatalogResponse: {
            /** Count */
            count: number;
            data_status: components["schemas"]["DataStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Items */
            items: components["schemas"]["StormSummary"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
        };
        /** StormDetail */
        StormDetail: {
            /**
             * Ace
             * @default null
             */
            ace: number | null;
            basin: components["schemas"]["Basin"];
            /**
             * Classic
             * @default false
             */
            classic: boolean;
            /**
             * Classic Rank
             * @default null
             */
            classic_rank: number | null;
            data_status: components["schemas"]["DataStatus"];
            /** Duration Hours */
            duration_hours: number;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Id */
            id: string;
            impact: components["schemas"]["StormImpact"];
            /**
             * Impact Available
             * @default false
             */
            impact_available: boolean;
            /**
             * Impact Score
             * @default null
             */
            impact_score: number | null;
            /**
             * Landfall Count
             * @default 0
             */
            landfall_count: number;
            /**
             * Max Wind Ms
             * @default null
             */
            max_wind_ms: number | null;
            /**
             * Min Pressure Hpa
             * @default null
             */
            min_pressure_hpa: number | null;
            /** Name */
            name: string;
            /**
             * Reported Damage Usd 2024
             * @default null
             */
            reported_damage_usd_2024: number | null;
            /**
             * Reported Deaths
             * @default null
             */
            reported_deaths: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Score Coverage
             * @default 0
             */
            score_coverage: number;
            /** Season */
            season: number;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Track */
            track: components["schemas"]["TrackPoint"][];
            /**
             * Wind Available
             * @default false
             */
            wind_available: boolean;
        };
        /** StormImpact */
        StormImpact: {
            /**
             * Estimated Exposed Population
             * @default null
             */
            estimated_exposed_population: number | null;
            /**
             * Reported Affected Population
             * @default null
             */
            reported_affected_population: number | null;
            /**
             * Reported Damage Usd 2024
             * @default null
             */
            reported_damage_usd_2024: number | null;
            /**
             * Reported Deaths
             * @default null
             */
            reported_deaths: number | null;
            /**
             * Warning
             * @default null
             */
            warning: string | null;
            /**
             * Wind Footprint Area Km2
             * @default null
             */
            wind_footprint_area_km2: number | null;
        };
        /** StormImpactResponse */
        StormImpactResponse: {
            data_status: components["schemas"]["DataStatus"];
            /**
             * Estimated Exposed Population
             * @default null
             */
            estimated_exposed_population: number | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Reported Affected Population
             * @default null
             */
            reported_affected_population: number | null;
            /**
             * Reported Damage Usd 2024
             * @default null
             */
            reported_damage_usd_2024: number | null;
            /**
             * Reported Deaths
             * @default null
             */
            reported_deaths: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /** Storm Id */
            storm_id: string;
            /**
             * Warning
             * @default null
             */
            warning: string | null;
            /**
             * Wind Footprint Area Km2
             * @default null
             */
            wind_footprint_area_km2: number | null;
        };
        /** StormSummary */
        StormSummary: {
            /**
             * Ace
             * @default null
             */
            ace: number | null;
            basin: components["schemas"]["Basin"];
            /**
             * Classic
             * @default false
             */
            classic: boolean;
            /**
             * Classic Rank
             * @default null
             */
            classic_rank: number | null;
            data_status: components["schemas"]["DataStatus"];
            /** Duration Hours */
            duration_hours: number;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** Id */
            id: string;
            /**
             * Impact Available
             * @default false
             */
            impact_available: boolean;
            /**
             * Impact Score
             * @default null
             */
            impact_score: number | null;
            /**
             * Landfall Count
             * @default 0
             */
            landfall_count: number;
            /**
             * Max Wind Ms
             * @default null
             */
            max_wind_ms: number | null;
            /**
             * Min Pressure Hpa
             * @default null
             */
            min_pressure_hpa: number | null;
            /** Name */
            name: string;
            /**
             * Reported Damage Usd 2024
             * @default null
             */
            reported_damage_usd_2024: number | null;
            /**
             * Reported Deaths
             * @default null
             */
            reported_deaths: number | null;
            /**
             * Score Coverage
             * @default 0
             */
            score_coverage: number;
            /** Season */
            season: number;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Wind Available
             * @default false
             */
            wind_available: boolean;
        };
        /** StormTrackResponse */
        StormTrackResponse: {
            data_status: components["schemas"]["DataStatus"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /** Storm Id */
            storm_id: string;
        };
        /** TaiwanZoneCollection */
        TaiwanZoneCollection: {
            data_status: components["schemas"]["DataStatus"];
            /** Features */
            features: components["schemas"]["TaiwanZoneFeature"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /** TaiwanZoneFeature */
        TaiwanZoneFeature: {
            /** Geometry */
            geometry: components["schemas"]["PolygonGeometry"] | components["schemas"]["MultiPolygonGeometry"];
            /**
             * Id
             * @default null
             */
            id: string | null;
            properties: components["schemas"]["TaiwanZoneProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** TaiwanZoneProperties */
        TaiwanZoneProperties: {
            /** Area Km2 */
            area_km2: number;
            /** Centroid Lat */
            centroid_lat: number;
            /** Centroid Lon */
            centroid_lon: number;
            /** County Code */
            county_code: string;
            data_status: components["schemas"]["DataStatus"];
            /** Name Zh */
            name_zh: string;
            /**
             * Population
             * @default null
             */
            population: number | null;
            /**
             * Population Year
             * @default null
             */
            population_year: number | null;
            /** Source Ids */
            source_ids?: string[];
            /**
             * Town Code
             * @default null
             */
            town_code: string | null;
            /** Zone Id */
            zone_id: string;
        };
        /** TrackFeature */
        TrackFeature: {
            basin: components["schemas"]["Basin"];
            /** Geographic Points */
            geographic_points: components["schemas"]["GeoPoint"][];
            /** Normalized Points */
            normalized_points: components["schemas"]["NormalizedPoint"][];
            /** Season */
            season: number;
            /** Storm Id */
            storm_id: string;
        };
        /** TrackPoint */
        TrackPoint: {
            /**
             * Category
             * @default null
             */
            category: string | null;
            /**
             * Is Landfall
             * @default null
             */
            is_landfall: boolean | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Moving Speed Kmh
             * @default null
             */
            moving_speed_kmh: number | null;
            /**
             * Pressure Hpa
             * @default null
             */
            pressure_hpa: number | null;
            /**
             * Source Agency
             * @default null
             */
            source_agency: string | null;
            /**
             * Storm Status
             * @default null
             */
            storm_status: string | null;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /**
             * Wind Ms
             * @default null
             */
            wind_ms: number | null;
        };
        /** TrajectoryFilters */
        TrajectoryFilters: {
            /** Basins */
            basins?: components["schemas"]["Basin"][];
            /**
             * Season From
             * @default 1840
             */
            season_from: number;
            /**
             * Season To
             * @default 2200
             */
            season_to: number;
        };
        /** TrajectoryMatch */
        TrajectoryMatch: {
            /** Direction Component */
            direction_component: number;
            /** Explanation */
            explanation: string;
            /** Frechet Component */
            frechet_component: number;
            /** Rank */
            rank: number;
            /** Similarity */
            similarity: number;
            /** Storm Id */
            storm_id: string;
        };
        /**
         * TrajectoryMatchMode
         * @enum {string}
         */
        TrajectoryMatchMode: "geographic" | "shape";
        /** TrajectoryMatchRequest */
        TrajectoryMatchRequest: {
            filters?: components["schemas"]["TrajectoryFilters"];
            mode: components["schemas"]["TrajectoryMatchMode"];
            /** Points */
            points: components["schemas"]["GeoPoint"][];
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** TrajectoryMatchResponse */
        TrajectoryMatchResponse: {
            /**
             * Data Status
             * @default algorithmic_result
             * @constant
             */
            data_status: "algorithmic_result";
            /** Elapsed Ms */
            elapsed_ms: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Items */
            items: components["schemas"]["TrajectoryMatch"][];
            mode: components["schemas"]["TrajectoryMatchMode"];
            /**
             * Normalized Point Count
             * @default 64
             */
            normalized_point_count: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WindFrame */
        WindFrame: {
            /** Dataset Id */
            dataset_id: string;
            /** Height */
            height: number;
            /**
             * Missing Value
             * @default null
             */
            missing_value: number | null;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** U */
            u: (number | null)[];
            /** V */
            v: (number | null)[];
            /** Width */
            width: number;
        };
        /** WindFrameReference */
        WindFrameReference: {
            /**
             * Byte Size
             * @default null
             */
            byte_size: number | null;
            /**
             * Sha256
             * @default null
             */
            sha256: string | null;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Url */
            url: string;
        };
        /** WindManifest */
        WindManifest: {
            bounds: components["schemas"]["GeoBounds"];
            data_status: components["schemas"]["DataStatus"];
            /** Dataset Id */
            dataset_id: string;
            /** Frames */
            frames: components["schemas"]["WindFrameReference"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Grid Order
             * @default north_to_south_west_to_east_row_major
             * @constant
             */
            grid_order: "north_to_south_west_to_east_row_major";
            /** Height */
            height: number;
            mode: components["schemas"]["WindMode"];
            /** Resolution Degrees */
            resolution_degrees: number;
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Source Ids */
            source_ids?: string[];
            /**
             * Storm Id
             * @default null
             */
            storm_id: string | null;
            /**
             * Units
             * @default m/s
             * @constant
             */
            units: "m/s";
            /** Width */
            width: number;
        };
        /**
         * WindMode
         * @enum {string}
         */
        WindMode: "global" | "storm";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    data_sources_api_data_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSourceListResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    impact_grid_api_impact_grid_get: {
        parameters: {
            query?: {
                storm_id?: string | null;
                window_id?: string | null;
                metric?: string | null;
                bbox?: string | null;
                hazard_threshold?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactGridCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"][];
                };
            };
        };
    };
    create_scenario_api_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scenario_api_scenarios__scenario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_scenario_api_scenarios__scenario_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facilities_api_scenarios__scenario_id__facilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_facility_api_scenarios__scenario_id__facilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_facility_api_scenarios__scenario_id__facilities__facility_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_facility_api_scenarios__scenario_id__facilities__facility_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
                facility_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storms_api_storms_get: {
        parameters: {
            query?: {
                basin?: string | null;
                classic?: boolean | null;
                season_from?: number | null;
                season_to?: number | null;
                min_wind_ms?: number | null;
                landfall?: boolean | null;
                sort_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormCatalogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_detail_api_storms__storm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_impact_api_storms__storm_id__impact_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storm_track_api_storms__storm_id__track_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                storm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormTrackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wind_frame_api_storms__storm_id__wind_frames__frame_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storm_id: string;
                frame_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindFrame"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wind_manifest_api_storms__storm_id__wind_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sample_wind_frame_api_storms__storm_id__wind_sample_frame_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindFrame"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taiwan_facilities_api_taiwan_facilities_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["FacilityType"] | null;
                county_code?: string | null;
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacilityCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taiwan_zones_api_taiwan_zones_get: {
        parameters: {
            query?: {
                county_code?: string | null;
                bbox?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaiwanZoneCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trajectory_match_api_trajectory_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrajectoryMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    period_wind_manifest_api_wind_periods__period_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WindManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
